# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-04-25 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='data',
            new_name='date',
        ),
    ]
